import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export default new Vuex.Store({
 state: {
  members: [
   {
    no: 1,
    name: "TRIANA RADITA INDRAWATI",
    gender: "Perempuan",
    city: "Bangkalan",
    photo: "https://u.ph.edim.co/da4d/108932855_3_140.png",
    instagram: "https://www.instagram.com/trianaradita/",
    facebook: "https://web.facebook.com/triana.r.indrawati?_rdc=1&_rdr",
    twitter: "",
    youtube: "https://www.youtube.com/channel/UCagRza7VOcsiRkg2KF57Xow",
    github: "",
   },
   {
    no: 2,
    name: "WIDYA CAHYA NINGTIAS",
    gender: "Perempuan",
    city: "Pamekasan",
    photo: "",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 3,
    name: "NISAA KAMILA RAHMATILLAH",
    gender: "Perempuan",
    city: "Surabaya",
    photo: "https://u.ph.edim.co/b0e0/108670621_4_140.png",
    instagram: "https://www.instagram.com/nisaa.kamila/",
    facebook: "https://web.facebook.com/kamila.nisaa",
    twitter: "https://twitter.com/nisaa_kamila",
    youtube: "https://www.youtube.com/channel/UC3TvCIF0CI0idkhfr7gD3vg",
    github: "https://github.com/kamilarahmatillah",
   },
   {
    no: 4,
    name: "M. SONI SETIAWAN",
    gender: "Laki - Laki",
    city: "Lamongan",
    photo:
     "https://scontent.fsub5-1.fna.fbcdn.net/v/t1.0-9/13939590_826034770831328_8625784647743405732_n.jpg?_nc_cat=107&_nc_sid=8bfeb9&_nc_eui2=AeHrE63oNHpJEyALoAbnzd9fV6KM8nYQTtdXoozydhBO19Uz4i6BYWCKpmWRCFexkm5HMZ3FdAm1kzKDQLV8D2Wk&_nc_ohc=s36n01mCMDcAX8gf5NU&_nc_ht=scontent.fsub5-1.fna&oh=0f2bd23a7adbf883b5df7805542e403e&oe=5F42BE22",
    instagram: "",
    facebook: "https://web.facebook.com/sony.setiawan.5",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 5,
    name: "IFUL ROSIDI",
    gender: "Laki - Laki",
    city: "Mojokerto",
    photo: "https://u.ph.edim.co/cfbd/108932955_3_140.png",
    instagram: "https://www.instagram.com/ifulrosidi/",
    facebook: "https://web.facebook.com/ifulrozidi",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 6,
    name: "IQBAL ADIYATMA",
    gender: "Laki - Laki",
    city: "Jombang",
    photo: "https://u.ph.edim.co/8245/112631085_5_140.jpg",
    instagram: "",
    facebook: "https://web.facebook.com/iqbal.adiyatma",
    twitter: "",
    youtube: "https://www.youtube.com/channel/UCuiQYOz5cbU9RwP0n-_L-uA",
    github: "",
   },
   {
    no: 7,
    name: "AGUS RIYANTO SUTOMO",
    gender: "Laki - Laki",
    city: "Pamekasan",
    photo: "https://u.ph.edim.co/4d0d/108668245_4_140.jpg",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 8,
    name: "TIYA JAYANTI",
    gender: "Perempuan",
    city: "Sumenep",
    photo: "https://u.ph.edim.co/2df4/109526677_3_140.png",
    instagram: "https://www.instagram.com/tyajyt/",
    facebook: "https://web.facebook.com/tiya.jayanti",
    twitter: "",
    youtube: "https://www.youtube.com/channel/UC12NV-yyP22-Q5BjtrfEt_w",
    github: "https://github.com/tiyajayanti",
   },
   {
    no: 9,
    name: "ROSALIA SUKMAWATI",
    gender: "Perempuan",
    city: "Bangkalan",
    photo: "https://u.ph.edim.co/315e/108939665_3_140.png",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 10,
    name: "SAFIRA ROHMATUL LAILY",
    gender: "Perempuan",
    city: "Surabaya",
    photo: "https://u.ph.edim.co/9c7b/108932427_3_140.png",
    instagram: "https://www.instagram.com/safira_laily98/",
    facebook: "https://web.facebook.com/fiierach.brcmchdyieryiemuch",
    twitter: "",
    youtube: "https://www.youtube.com/channel/UCFiGIO-sPVgaUWNDcPZi7nw",
    github: "",
   },
   {
    no: 11,
    name: "Moh. Zulham Effendy",
    gender: "Laki - Laki",
    city: "Sidoarjo",
    photo:
     "https://avatars2.githubusercontent.com/u/38505192?s=460&u=dc6b2da1b70ed3a9f8213a82acfff9d3715f64b2&v=4",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "https://github.com/zulhamfendhy",
   },
   {
    no: 12,
    name: "MOHAMMAD FARIS AZHAR",
    gender: "Laki - Laki",
    city: "Bangkalan",
    photo: "https://u.ph.edim.co/be3d/113177265_6_140.png",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 13,
    name: "WENI PRATIWI S.",
    gender: "Perempuan",
    city: "Bangkalan",
    photo: "https://u.ph.edim.co/4c88/108939891_4_140.jpg",
    facebook: "",
    twitter: "https://twitter.com/weni_wps",
    youtube: "https://www.youtube.com/channel/UCkdeOtZ2J4WLcdfuUVR2cnw",
    github: "",
   },
   {
    no: 14,
    name: "YUNI INDAH SUSILANA SARI",
    gender: "Perempuan",
    city: "Bangkalan",
    photo: "https://u.ph.edim.co/4b8d/112198977_3_140.jpg",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "https://www.youtube.com/channel/UC7Ws48h4NgisyNxVLv0dEdA",
    github: "",
   },
   {
    no: 15,
    name: "AISY QONITAH SUWARDI",
    gender: "Perempuan",
    city: "Bangkalan",
    photo: "https://u.ph.edim.co/fba5/87745541_3_140.jpg",
    instagram: "https://www.instagram.com/aisyqonitah/",
    facebook: "https://web.facebook.com/aisy.qonitah",
    twitter: "https://twitter.com/aisyqonitah",
    youtube: "https://www.youtube.com/channel/UC9yL_rTFBYw25tt6Rtb4JmA",
    github: "",
   },
   {
    no: 16,
    name: "MIFTAHUL JANNAH",
    gender: "Perempuan",
    city: "Bangkalan",
    photo: "https://u.ph.edim.co/868c/109484269_5_140.png",
    instagram: "https://www.instagram.com/saya_miftah/",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 17,
    name: "DICKY DWI RYANTIARNO",
    gender: "Laki - Laki",
    city: "Lamongan",
    photo: "https://u.ph.edim.co/60ee/108930619_1_140.jpg",
    instagram: "https://www.instagram.com/dicky.dwi.r/",
    facebook: "https://web.facebook.com/dicky.dwi.r",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 18,
    name: "Husna",
    gender: "Laki - Laki",
    city: "",
    photo: "https://u.ph.edim.co/6c03/122958312_1_140.jpg",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 19,
    name: "",
    gender: "Laki - Laki",
    city: "",
    photo: "",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 20,
    name: "",
    gender: "Laki - Laki",
    city: "",
    photo: "",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 21,
    name: "",
    gender: "Laki - Laki",
    city: "",
    photo: "",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 22,
    name: "",
    gender: "Laki - Laki",
    city: "",
    photo: "",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 23,
    name: "",
    gender: "Laki - Laki",
    city: "",
    photo: "",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 24,
    name: "",
    gender: "Laki - Laki",
    city: "",
    photo: "",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 25,
    name: "",
    gender: "Laki - Laki",
    city: "",
    photo: "",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 26,
    name: "",
    gender: "Laki - Laki",
    city: "",
    photo: "",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 27,
    name: "",
    gender: "Laki - Laki",
    city: "",
    photo: "",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "",
   },
   {
    no: 28,
    name: "",
    gender: "Laki - Laki",
    city: "",
    photo: "",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    github: "",
   },
  ],
 },
 mutations: {},
 actions: {},
});
